### ISSUE TITLE
Kafka::UnknownMemberId or Kafka::OffsetCommitError not raised or noticed

### ISSUE THREAD

**Issue by dafeiner** [karafka/karafka#505] opened 2019-05-16 02:42 UTC
We had some long running batch processing that lead to `Kafka::UnknownMemberId` errors logged. Similar to https://github.com/zendesk/ruby-kafka/issues/561 

Our logs repeated:

```
app/karafka_server.1:  E, [2019-05-14T14:35:02.777524 #4] ERROR -- : Error committing offsets: Kafka::UnknownMemberId
```

https://github.com/zendesk/ruby-kafka/blob/720401a5af7d3d2e4fa5a6717feaf16c467d648f/lib/kafka/consumer_group.rb#L95-L97

```
 app/karafka_server.1:  E, [2019-05-14T14:35:02.778675 #4] ERROR -- : Failed to join group; resetting member id and retrying in 1s... 
```

https://github.com/zendesk/ruby-kafka/blob/720401a5af7d3d2e4fa5a6717feaf16c467d648f/lib/kafka/consumer_group.rb#L155-L156

However it doesn't appear that these errors are rescued and noticed by the monitor like other errors:

https://github.com/karafka/karafka/blob/4208838bac6d7e4846c3730c6bc30bfeed787d0f/lib/karafka/connection/client.rb#L42-L49

We are using the pretty standard newrelic listener (since deleted from the wiki), but it is just subscribing to the events that end in `_error`.  

Are we missing something or is there a way to rescue more of the the errors from the `ruby-kafka` library and send them to NewRelic?

Thanks!

**Comment by mensfeld** [comment] 2019-05-17 07:45
Hey. Thank you for the report. I will investigate shortly.

Sidenote:

> We are using the pretty standard newrelic listener (since deleted from the wiki)

The Newrelic listener was removed from the wiki, because Newrelic didn't give a shi*t about providing me with a commercial account on which I could test the Karafka listener and they told me to pay for one. I could but I don't plan on investing my private money to do commercial work for other companies for free.


Feel free to forward them this info ;)

**Comment by mensfeld** [comment] 2019-05-17 07:57
Hey @dafeiner did you try hooking up here?

> Karafka.monitor.instrument('connection.listener.fetch_loop.error', caller: self, error: e)

https://github.com/karafka/karafka/blob/master/lib/karafka/connection/listener.rb#L47

**Comment by mensfeld** [comment] 2019-05-17 08:16
Ok. We need to catch those, instrument and reraise. The flow won't be changed so things should work smooth. I will produce fix and backport to 1.2 for you soon.

**Comment by mensfeld** [comment] 2019-05-17 09:12
Ok. It's not a bug but lack of the instrumentation on the ruby-kafka level background processing mechanism on your side for the newrelic. Some of the Kafka internal errors don't bubble up (https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L406) as they are taken care of within the internal ruby-kafka flow. I'm not a big fan of this solution but I do see benefits of it.

Here's a POC for you that will track this type of exceptions. For the more extensive newrelic example, please refer to karafka and kafka related newrelic docs (irony).

```
ActiveSupport::Notifications.subscribe('loop.consumer.kafka') do |*args|
  event = ActiveSupport::Notifications::Event.new(*args)
  byebug if event.payload[:exception]
end
```

this should allow you to instrument things like that.

I also don't want to "proxy pass" ruby-kafka instrumentation to Karafka as it would create too many confusion.

I will update the instrumentation docs to cover this case in a "general" way.

If this answer is sufficient, feel free to close the issue.

**Comment by mensfeld** [comment] 2019-05-25 11:35
I'm closing it for now. Feel free to open if you feel, that the answer is insufficient or if you need any other help.

**Closed by mensfeld** 2019-05-25 11:35 UTC
