### ISSUE TITLE
Pointers on ACID, transactions, etc?

### ISSUE THREAD

**Issue by bemurphy** [karafka/karafka#445] opened 2019-01-06 19:01 UTC
Hey @mensfeld. First off, thanks again for this framework!

Do you have any pointers to talks, blog posts, or articles around the following two area?

In a production app, how do you try and build more distributed consistency between writes to a local RDBMS and producing the message in Kafka? My first thought was "wrap it in a DB transaction", but I always cringe a little binding a db transaction alongside network i/o to another service. I'm imagining, for instance, a scenario where the network path to the RDBMS is good, but the path to Kafka hiccups.

I believe you referenced my second concern in a previous talk, but was hoping you could elaborate on it. Say code from a Rails app produces a `video_created` message, and initially, you just consume this message to run processing to re-encode and upload the new videos to S3. Later, the product gets a requirement to also send an email to the uploader ("we've started processing your video"), and then later, also update some metrics, all from the same message. What is your preferred way for adding to the chain of work from a single message in a more decoupled way, and having some (obviously not all) ACID properties?

**Comment by bemurphy** [comment] 2019-01-06 19:05
My initial thought on the second area is to just create a new class (command, interaction, service, whatever you want to call it) that handles the discrete operation, and just add a new line that calls it from the `Consumer#consume` method. I'm wondering if you have a more elegant approach you like to use.

**Comment by bemurphy** [comment] 2019-01-09 17:11
No rush! I appreciate any insights you might have, thanks.

**Comment by mensfeld** [comment] 2019-01-21 13:21
Ok. It took me more time than I initially wanted. Sorry for that. 

> Do you have any pointers to talks, blog posts, or articles around the following to area?

No, but I would love to see some or even blog about that. The problem is the same as always: time :(

> In a production app, how do you try and build more distributed consistency between writes to a local RDBMS and producing the message in Kafka?

That sucks as there is no transaction support for Waterdrop and Karafka as there is no transaction support for rdkafka (yet) and I'm waiting to get it. See https://github.com/karafka/karafka/issues/431

To partially (not completely) bypass that problem I do two things:

- Try to design any system that operates on Kafka data with a reentrancy
- Use RDBS with Karafka responders and transactions

About the second one:

If you go with responders instead of direct Waterdrop usage, it not only checks the proper dispatching of the messages but also buffers them (https://github.com/karafka/karafka/blob/master/lib/karafka/base_responder.rb#L194). Then once we have all the things that should happen in the DB (apart from committing the transaction) I do broadcast the events. That way if anything goes badly (almost anything) the data shouldn't be transmitted. Ofc it does not cover the `kill -9` case but drastically lowers problems related to a "typical" flow inconsistency. Also, karafka upon receiving a terminate signal will finish any job it is currently running, so no problem there as well.

> for instance, a scenario where the network path to the RDBMS is good, but the path to Kafka hiccups.

Karafka has a retry built in :), so if the hickup is not dramatic, it will work. Also, any service is an external service :D DB as well as Kafka ;)

> Say code from a Rails app produces a video_created message, and initially, you just consume this message to run processing to re-encode and upload the new videos to S3. Later, the product gets a requirement to also send an email to the uploader ("we've started processing your video"), and then later, also update some metrics, all from the same message. What is your preferred way for adding to the chain of work from a single message in a more decoupled way, and having some (not all) ACID properties?

Well you've touched a huge subject sir (on which I plan to do an article) about topic naming. In the above example the answer would be: it depends.

And it is really app specific as you can have `videos_created` topic that also indicates state, but you could also broadcast all the state changes into a `videos` topic. Each has its advantages and disadvantages. I recently use more often general resource topics in which I do indicate the resource state change like so:

```ruby
      respond_to(
        :commit_builds,
        builder.send(
          commit_build.process_state,
          commit_build
        ),
        key: commit_build.id
      )
```

with a builder like that:

```ruby
# frozen_string_literal: true

# Wraps up a builder for generating a pretty JSON with a internal compatible format
# with the event type included
module ResponseBuilder
  class << self
    # @param method_name [Symbol] method name
    # @param args [Array] arguments
    # @return [Hash] Hash with an event and resource
    # @example
    #   Karafka::Coditsu::ResponseBuilder.created(1) #=> { resource: 1, event: :created }
    def method_missing(method_name, *args, &block)
      return super unless args.size == 1
      return super if block

      {
        resource: args[0],
        event: method_name
      }
    end

    # @param _method_name [Symbol] name of method
    # @param _include_private [Boolean] should be included in private checks
    # @return [Boolean] do we take care of this missing method
    def respond_to_missing?(_method_name, _include_private = false)
      true
    end
  end
end
```

When broadcasting all the state changes / events into a single topic, I can use kafka keys and ordering much more efficiently, however I do increase number of messages that are being sent and that have to be processes (or discarded) per topic. Anyhow to answer you question:

> . Later, the product gets a requirement to also send an email to the uploader ("we've started processing your video")

That should be a separate event upon which a separate app reacts. You can either broadcast the owner with the video or you can use API endpoint or a materialized data within it's own aggregation root to do that.

**Comment by mensfeld** [comment] 2019-01-21 13:22
I'm closing that but feel free to discuss with me :) Once we reach a good state, I will move some of it into the wiki.

**Closed by mensfeld** 2019-01-21 13:22 UTC
Labels: documentation, question
