### ISSUE TITLE
listener fetch loop error  undefined method > 'nil:class'

### ISSUE THREAD

**Issue by keshavg2** [karafka/karafka#1693] opened 2023-10-26 21:27 UTC
Listener fetch loop error: undefined method `>' for nil:NilClass
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/messages/builders/batch_metadata.rb:54:in `local_created_at'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/messages/builders/batch_metadata.rb:29:in `call'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/messages/builders/messages.rb:20:in `call'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/processing/executor.rb:54:in `before_enqueue'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/processing/jobs/consume.rb:25:in `before_enqueue'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/connection/listener.rb:283:in `each'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/connection/listener.rb:283:in `build_and_schedule_consumption_jobs'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/connection/listener.rb:123:in `fetch_loop'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/connection/listener.rb:55:in `call'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/karafka-2.2.9/lib/karafka/helpers/async.rb:28:in `block in async_call'
/home/hp/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:435:in `block (2 levels) in thread_block_with_current_transaction'

When I run the `bundle exec karafka server` I'm getting the above error
--------
## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## Your setup details

Please provide Kafka version and the output of `karafka info` or `bundle exec karafka info` if using Bundler.

Here's an example:

```
$ [bundle exec] karafka info
Karafka version: 2.2.9
Ruby version: 3.2.0
Ruby-kafka version: 0.7.9
Application client id: karafka-local
Backend: inline
Batch fetching: true
Batch consuming: true
Boot file: /app/karafka/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://kafka:9092"]
```

**Comment by mensfeld** [comment] 2023-10-27 04:49
@keshavg2 what kafka version are you using (kafka, not karafka)?

**Comment by keshavg2** [comment] 2023-10-27 06:10
Hi, @mensfeld I'm not sure about the Kafka version because we are using Kafka from the vendor. but the issue is not getting the timestamp in your last message.

**Comment by mensfeld** [comment] 2023-10-27 07:28
@keshavg2 unless you provide me with brokers version I cannot help you. I know exactly what the issue is however I may or may not fix this depending on the cluster version.

**Comment by mensfeld** [comment] 2023-10-27 07:34
Most likely you are using Kafka pre 0.11 and fetch API v1 that has a different (old) message structure that is no longer supported:

```
v0
Message => Crc MagicByte Attributes Key Value
  Crc => int32
  MagicByte => int8
  Attributes => int8
  Key => bytes
  Value => bytes
  
v1 (supported since 0.10.0)
Message => Crc MagicByte Attributes Key Value
  Crc => int32
  MagicByte => int8
  Attributes => int8
  Timestamp => int64
  Key => bytes
  Value => bytes
```

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets

It is 6 years old.

**Comment by mensfeld** [comment] 2023-10-27 07:35
Of course I accept it may be a karafka bug but until you can prove it and replicate this with https://github.com/karafka/example-apps I won't do anything with it.

If you want this to be mitigated and you consider this a business critical case, I am willing to add support this in the Enterprise offering.

**Comment by mensfeld** [comment] 2023-10-27 07:59
ref: https://karafka.io/docs/Versions-Lifecycle-and-EOL/#kafka-versions-support

**Comment by keshavg2** [comment] 2023-10-30 18:53
hi @mensfeld I'm using this kafka version ```kafka_2.13-3.5```.

**Comment by keshavg2** [comment] 2023-10-31 06:31
@mensfeld No Messages are not old. I'm getting this type of message in my cluster.
```{"topic":"click2call","partition":0,"offset":389,"tstype":"create","ts":-1,"broker":-1,"key":"CHANNEL_HANGUP","payload":"{\"Event-Name\": \"CHANNEL_HANGUP\", \"UUID\": \"0e21d552-6126-40e6-9816-709abb611c11\", \"Content-Type\": \"Event\", \"Timestamp\": 1698501177.0, \"meta\": {\"Hangup-Cause\": \"NORMAL_CLEARING\", \"Phone\": \"08885365062\", \"IVR_MENU_STATUS\": null, \"SOUND_FILE\": null, \"CALL_STATE\": \"ACTIVE\", \"node\": \"lintel-vocie-broadcasting-test.novalocal\", \"module\": \"click2call\", \"topic\": \"click2call\", \"refno\": \"2341\"}}"}```

**Comment by mensfeld** [comment] 2023-10-31 08:36
@keshavg2 can you tell me what is the producer that produces this? Or how do you produce this data? It seems to be using V1 API and I want to understand the technical origins of this message.

**Comment by mensfeld** [comment] 2023-11-01 16:35
@keshavg2 after giving it a sceond thought I may support this if I get more details from you. This should not require extensive changes on my side but I do need to know how your messages are produced

**Comment by keshavg2** [comment] 2023-11-02 06:46
@mensfeld I think they are using python for creating the message for kafka. but I don't have much information about this because I'm using others kafka service. but I have also seen your code in this function local_created_at  in file lib/karafka/builders/batch_metadata.rb. I think we have to improve this also because if we did not get the timestamp it will compare with nil and It will throw error.

**Comment by mensfeld** [comment] 2023-11-02 08:00
@keshavg2 I know how and where to fix it :) no worries about that

**Comment by mensfeld** [comment] 2023-11-03 13:14
@keshavg2 I should improve this in Q1 2024.

**Comment by mensfeld** [comment] 2024-03-05 15:07
Closing. ATM I do not have plans to bring it unless there is incentive to it or more users wanting old API version.

**Closed by mensfeld** 2024-03-05 15:07 UTC
Labels: enhancement
